class MockAIService {
  static async processVideo(videoData) {
    console.log(`Mock AI processing video: ${videoData.title}`);
    
    // Simulate processing time
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    // Return JSON strings for SQLite compatibility
    return {
      transcript: `This is a mock transcript for "${videoData.title}". AI has processed this video and generated captions, script, and editing suggestions.`,
      aiScript: `[AI Generated Script]\n\nIntroduction (0:00-0:15):\nWelcome to this tutorial. Today we'll learn about building full-stack applications.\n\nMain Content (0:15-2:30):\nFirst, we set up the backend with Express and SQLite. Then we create the React frontend.\n\nConclusion (2:30-3:00):\nThat's it! You've built a complete application.`,
      captions: `WEBVTT

1
00:00:00.000 --> 00:00:05.000
Welcome to this tutorial on building
a Clueso clone application

2
00:00:05.000 --> 00:00:10.000
Today we'll learn about full-stack
development with React and Express`,
      cuts: JSON.stringify([
        { start: 0, end: 15, reason: "Introduction" },
        { start: 15, end: 150, reason: "Main tutorial" },
        { start: 150, end: 180, reason: "Conclusion" }
      ]),
      voiceover: "ai-voiceover-sample.mp3",
      zoomPoints: JSON.stringify([
        { timestamp: 10, scale: 1.5, duration: 5 },
        { timestamp: 45, scale: 2.0, duration: 3 }
      ]),
      status: "completed"
    };
  }
  
  static async generateThumbnail(videoPath) {
    // Mock thumbnail generation
    return `thumbnail-${Date.now()}.jpg`;
  }
  
  static async transcribeAudio(audioPath) {
    await new Promise(resolve => setTimeout(resolve, 2000));
    return "This is mock transcription text generated by AI.";
  }
}

module.exports = MockAIService;